name: Build and Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
    contents: write
    
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ] # windows-latest
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6
      
      - if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo chmod +x -R .

      - run: |
          ./local-init.sh
          echo $BOARD
        
      - name: Archive SDK
        working-directory: "mcuxpresso-sdk"
        run: |
          zip -s 100m --symlinks -r "${{ github.event.repository.name }}-mcuxpresso-sdk-${{ github.ref_name }}-${{ matrix.os }}.zip" .
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "cmake-build"
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cmake-build/${{ github.event.repository.name }}-${{ github.ref_name }}-${{ matrix.os }}.zip,mcuxpresso-sdk/${{ github.event.repository.name }}-mcuxpresso-sdk-${{ github.ref_name }}-${{ matrix.os }}.z*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
