name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
permissions:
    contents: write
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v6

      - run: sudo chmod +x -R .
      
      - run: ./local-init.sh

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "cmake-build"
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}.zip"
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "mcuxpresso-sdk"
          filename: "${{ github.event.repository.name }}-mcuxpresso-sdk-${{ github.ref_name }}.zip"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "cmake-build/${{ github.event.repository.name }}-${{ github.ref_name }}.zip,mcuxpresso-sdk/${{ github.event.repository.name }}-mcuxpresso-sdk-${{ github.ref_name }}.zip"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
